Updated utils.compat.Directive import
Fix this error:

Could not import extension sphinxcontrib.github (exception: cannot import name 'Directive' from 'sphinx.util.compat' (/home/omar/.local/lib/python3.7/site-packages/sphinx/util/compat.py))

sphinx.util.compat.Directive has been deprecated